USE heroku_87f2326f0160a00 ;

DROP TABLE TB_GEO_BARRIO;
DROP TABLE TB_GEO_LOCALIDAD;
DROP TABLE TB_GEO_CIUDAD;
DROP TABLE TB_GEO_DEPARTAMENTO;
DROP TABLE TB_GEO_PAIS;
DROP TABLE TB_PERS_PACIENTE;
DROP TABLE TB_PARAM_PARAMETRO_PERSONA;
DROP TABLE TB_PARAM_TIPO_PARAMETRO_PERSONA;

DROP TABLE TB_PROC_PROCEDIMIENTO;
DROP TABLE TB_MED_MEDICAMENTO;
DROP TABLE TB_PROD_PRODUCTO;
DROP TABLE TB_USU_USUARIO;