/* Populate tables */
INSERT INTO TB_PERS_PARAM_TIPO_PARAMETRO (TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(1, 'TIPIDENT', 'Tipos de identificación', 'Describe los tipos de identificación de los documentos de personas N o J', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_TIPO_PARAMETRO (TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(2, 'GENERO', 'Genero del paciente', 'Describe los generos del paciente', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_TIPO_PARAMETRO (TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(3, 'ESTCIVIL', 'Estado Civil', 'Describe los estados civiles', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_TIPO_PARAMETRO (TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(4, 'GRUPSANG', 'Grupo sanguineo', 'Describe los grupos sanguineos', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_TIPO_PARAMETRO (TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(5, 'NIVACAD', 'Nivel académico', 'Describe los niveles académicos', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_TIPO_PARAMETRO (TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(6, 'RAZA', 'Razas', 'Describe las razas', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_TIPO_PARAMETRO (TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(7, 'OCUPACION', 'Ocupación', 'Describe las ocupación', NOW(), 'A');

/* Populate tables */
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(1, 1, 'CC', 'CÉDULA DE CIUDADANIA', 'Tipo de documento cédula de ciudadania ', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(2, 1, 'TI', 'TARJETA DE IDENTIDAD', 'Tipo de documento tarjeta de identidad', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(3, 2, 'M', 'MASCULINO', 'Genero de pacinete masculino', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(4, 2, 'F', 'FEMENINO', 'Genero de pacinete femenino', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(5, 3, 'S', 'SOLTERO', 'Estado civil soltero', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(6, 3, 'S', 'CASADO', 'Estado civil casado', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(7, 4, 'OP', 'O+', 'Grupo sanguineo O positivo', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(8, 4, 'ON', 'O-', 'Grupo sanguineo O negativo', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(9, 5, 'PRI', 'PRIMARIA', 'Nivel académico primaria', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(10, 5, 'SEC', 'SECUNDARIA', 'Nivel académico secundaria', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(11, 6, 'AFR', 'AFRODECENDIENTE', 'Raza afrodecendiente', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(12, 6, 'IND', 'INDIGENA', 'Raza indigena', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(13, 7, 'EST', 'ESTUDIANTE', 'Ocupación estudiante', NOW(), 'A');
INSERT INTO TB_PERS_PARAM_PARAMETRO (PARAMETRO, TIPO_PARAMETRO, CODIGO, DESCRIPCION, OBSERVACION, FECHA_CREACION, ESTADO) VALUES(14, 7, 'EMP', 'EMPLEADO', 'Ocupación empleado', NOW(), 'A');

/* Populate tables */
INSERT INTO TB_PERS_PACIENTE (PACIENTE, PARAM_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, FECHA_NACIMIENTO, PARAM_GENERO, PARAM_ESTADO_CIVIL, PARAM_OCUPACION, DIRECCION_RESIDENCIA, TELEFONO_RESIDENCIA, CELULAR, EMAIL, PARAM_GRUPO_SANGUINEO, PARAM_NIVEL_ACADEMICO, PARAM_RAZA, ESTADO) VALUES  (1, 1, '67876788', 'CARLOS', 'ALBERTO', 'GONZALEZ', 'ORTIZ', NOW(), 3, 5, 13, 'CALLE 4 NO.23-58', '2789865', '31257955', 'loksh@hotmail.com', 7, 9, 11, 'A');
